name: directed_graph

description: Generic directed graph and weighted directed graph with algorithms
  enabling sorting and topological ordering of vertices.

version: 0.5.0

homepage: https://github.com/simphotonics/directed_graph

topics:
  - graph
  - directed-graph
  - topological
  - vertex

environment:
  sdk: '^3.9.2'

dependencies:
  collection: ^1.19.1
  exception_templates: ^0.3.2
  lazy_memo: ^0.2.5
  quote_buffer: ^0.2.7

dev_dependencies:
  benchmark_runner: ^2.0.1
  lints: ^6.0.0
  test: ^1.26.3
